# Generated by Django 4.1.2 on 2022-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('type_de_probleme', models.CharField(max_length=50)),
                ('niveau_du_probleme', models.CharField(max_length=100)),
                ('commentaire_sur_le_probleme', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('HOMME', 'HOMME'), ('FEMME', 'FEMME')], max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(default='admin@default.com', max_length=50)),
                ('telephone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='patient',
        ),
    ]
