# Generated by Django 4.1.1 on 2022-11-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0002_alerte_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerte',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
