# Generated by Django 4.1.2 on 2022-11-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0002_alerte_citoyen_delete_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='last_name',
        ),
    ]
