# Generated by Django 4.1.2 on 2022-11-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0003_remove_alerte_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='structure',
            field=models.CharField(default='ONEA', max_length=20),
        ),
    ]
