# Generated by Django 4.1.2 on 2022-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0004_alerte_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='cnib',
            field=models.CharField(default='B6541025410', max_length=50),
        ),
        migrations.AlterField(
            model_name='alerte',
            name='structure',
            field=models.CharField(default='SONABEL', max_length=20),
        ),
    ]
