# Generated by Django 4.1.2 on 2022-11-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0005_citoyen_cnib_alter_alerte_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerte1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('probleme', models.CharField(max_length=100)),
                ('commentaire', models.CharField(max_length=400)),
                ('struct', models.CharField(default='SONABEL', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='alerte',
            name='structure',
            field=models.CharField(default='ONEA', max_length=20),
        ),
    ]
