# Generated by Django 4.1.2 on 2022-11-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0006_alerte1_alter_alerte_structure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alerte1',
            old_name='commentaire',
            new_name='commentaire_sur_le_probleme',
        ),
        migrations.RenameField(
            model_name='alerte1',
            old_name='probleme',
            new_name='niveau_du_probleme',
        ),
        migrations.RenameField(
            model_name='alerte1',
            old_name='type',
            new_name='type_de_probleme',
        ),
    ]
