# Generated by Django 4.1.2 on 2022-11-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0007_rename_commentaire_alerte1_commentaire_sur_le_probleme_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alerte1',
        ),
    ]
