# Generated by Django 4.1.1 on 2022-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_first_Application', '0008_delete_alerte1'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='user_name',
            field=models.CharField(default='toto', max_length=30),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='telephone',
            field=models.CharField(default='64896986', max_length=20),
        ),
    ]
